# Azure Configuration Template
# Copy this file and replace with your actual Azure credentials
azure:
  # Storage Account Configuration
  storage_account:
    name: your_storage_account_name
    key: your_storage_account_key
    connection_string: your_connection_string
    
  # Data Lake Storage
  data_lake:
    container_raw: raw-data
    container_processed: processed-data
    container_results: ml-results
    
  # Azure SQL Database (optional)
  sql_database:
    server: your-azure-server.database.windows.net
    database: hospital_readmission
    user: your_username
    password: your_password
    
  # Azure Machine Learning (optional)
  ml_workspace:
    name: your-ml-workspace-name
    resource_group: your-resource-group
    subscription_id: your_subscription_id

# Environment Configuration
environment:
  development:
    use_local_mysql: true
    use_azure_storage: false
    
  production:
    use_local_mysql: false
    use_azure_storage: true 